apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  annotations:
    argocd-image-updater.argoproj.io/image-list: user-service=536697223481.dkr.ecr.us-east-1.amazonaws.com/order-service
    argocd-image-updater.argoproj.io/user-service.update-strategy: latest
    argocd-image-updater.argoproj.io/user-service.force-update: "true"
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: 536697223481.dkr.ecr.us-east-1.amazonaws.com/order-service:latest
        ports:
        - containerPort: 3002
